// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db_connect`, `default_layer`, `env_layer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `submit`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<App>>
abstract class App implements RustOpaqueInterface {
  Future<OldElection> downloadElection({
    required String url,
    required String id,
  });

  Stream<String> finalize({required Election election, required String lwd});

  Future<List<Election>> listElectionDefs();

  factory App({required String dbName}) =>
      RustLib.instance.api.crateApiAppAppNew(dbName: dbName);

  Future<Election> newElection({required String name});

  Future<void> scan({
    required String seed,
    required int start,
    required int end,
  });

  Future<void> storeElection({required Election election});
}
