// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'data.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `into`

@freezed
sealed class CandidateChoice with _$CandidateChoice {
  const factory CandidateChoice({required String choice}) = _CandidateChoice;
}

/// Details of an election, including metadata, candidates, and election parameters.
@freezed
sealed class Election with _$Election {
  const factory Election({
    required String name,
    String? seed,
    required int startHeight,
    required int endHeight,
    required List<Question> questions,
    required bool signatureRequired,
  }) = _Election;
}

@freezed
sealed class Question with _$Question {
  const factory Question({
    required String question,
    required List<CandidateChoice> choices,
  }) = _Question;
}
